CREATE TABLE library_cards (
    card_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    create_date DEFAULT SYSDATE DATE NOT NULL,
    valid_due_date DATE NOT NULL,
    CONSTRAINT pk_library_card PRIMARY KEY(card_id) 
);

CREATE TABLE Customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR2(50) NOT NULL,
    customer_lastname VARCHAR2(50) NOT NULL,
    customer_phone VARCHAR2(11),
    customer_birthdate DATE NOT NULL,
    card_id NUMBER,
    CONSTRAINT pk_customer PRIMARY KEY (customer_id),
    CONSTRAINT fk_customer_card FOREIGN KEY (card_id) REFERENCES library_cards(card_id) ON DELETE SET NULL
);

ALTER TABLE library_cards 
ADD customer_id NUMBER CONSTRAINT fk_card_customer REFERENCES Customers (customer_id) ON DELETE CASCADE;

CREATE TABLE Departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(126) NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (department_id)
);

CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_id NUMBER NOT NULL,
    employee_name VARCHAR2(50) NOT NULL,
    employee_lastname VARCHAR2(50) NOT NULL,
    employee_phone CHAR(11) NOT NULL,
    employee_uin CHAR(12) NOT NULL,
    employee_birthdate DATE NOT NULL,
    employment_date DATE NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (employee_id),
    CONSTRAINT fk_employee_department FOREIGN KEY (department_id) REFERENCES Departments (department_id) ON DELETE CASCADE
);

CREATE TABLE Languages (
    language_code VARCHAR2(2) NOT NULL CHECK (length(language_code) = 2),
    language_name VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_language PRIMARY KEY (language_code)
);

CREATE TABLE PUBLISHERS (
    PUBLISHER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    PUBLISHER_NAME VARCHAR2(126) NOT NULL,
    PUBLISHER_ADDRESS VARCHAR2(126),
    PUBLISHER_PHONE CHAR(11),
    publisher_email VARCHAR2(126),
    CONSTRAINT pk_publisher PRIMARY KEY (PUBLISHER_ID)
);

CREATE TABLE Authors (
    author_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    author_name VARCHAR2(50) NOT NULL,
    author_lastname VARCHAR2(50) NOT NULL,
    author_email VARCHAR2(126),
    CONSTRAINT pk_author PRIMARY KEY (AUTHOR_ID)
);

CREATE TABLE Book_Categories (
    category_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR2(256) NOT NULL,
    CONSTRAINT pk_book_category PRIMARY KEY (category_id)
);

CREATE TABLE Books (
    book_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    book_title VARCHAR2(256) NOT NULL,
    book_subtitle VARCHAR2(512),
    author_id NUMBER NOT NULL,
    publisher_id NUMBER,
    language_code VARCHAR2(2) CHECK (length(language_code) = 2),
    category_id NUMBER, 
    page_count NUMBER,
    publish_date DATE NOT NULL,
    isbn_13 CHAR(13),
    isbn_10 CHAR(10),
    CONSTRAINT pk_book PRIMARY KEY (book_id),
    CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES AUTHORS(AUTHOR_ID) ON DELETE CASCADE,
    CONSTRAINT fk_book_publisher FOREIGN KEY (publisher_id) REFERENCES Publishers (publisher_id) ON DELETE SET NULL,
    CONSTRAINT fk_book_language FOREIGN KEY (language_code) REFERENCES Languages (language_code) ON DELETE SET NULL,
    CONSTRAINT fk_book_category FOREIGN KEY (category_id) REFERENCES Book_Categories (category_id)  ON DELETE SET NULL
);

CREATE TABLE book_items (
    book_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    book_id NUMBER NOT NULL,
    CONSTRAINT pk_book_item PRIMARY KEY (book_item_id),
    CONSTRAINT fk_item_book FOREIGN KEY (book_id) REFERENCES Books(book_id)
);

CREATE TABLE Borrows_Books (
    borrow_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    book_item_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    employee_id NUMBER,
    due_date DATE NOT NULL,
    CONSTRAINT pk_borrow_book PRIMARY KEY (borrow_id),
    CONSTRAINT fk_borrow_customer FOREIGN KEY (customer_id) REFERENCES Customers (customer_id) ON DELETE CASCADE,
    CONSTRAINT fk_borrow_book FOREIGN KEY (book_item_id) REFERENCES book_items(book_item_id) ON DELETE CASCADE,
    CONSTRAINT fk_borrow_employee FOREIGN KEY (employee_id) REFERENCES Employees (employee_id) ON DELETE SET NULL

);

CREATE TABLE Magazines (
    magazine_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    magazine_title VARCHAR(126) NOT NULL,
    magazine_email VARCHAR(126),
    price NUMBER not null,
    edition_number NUMBER not null,
    PUBLISHER_ID NUMBER NOT NULL,
    CONSTRAINT pk_magazine PRIMARY KEY (magazine_id),
    CONSTRAINT FK_MAGAZINE_PUBLISHER FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS(PUBLISHER_ID)
);

CREATE TABLE magazine_items (
    magazine_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    magazine_id NUMBER NOT NULL,
    CONSTRAINT PK_MAGAZINE_ITEM PRIMARY KEY (MAGAZINE_ITEM_ID),
    CONSTRAINT FK_ITEM_MAGAZINE FOREIGN KEY (MAGAZINE_ID) REFERENCES MAGAZINES(MAGAZINE_ID) ON DELETE CASCADE
);

CREATE TABLE NEWSPAPERS (
    newspaper_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    newspaper_name VARCHAR(126) NOT NULL,
    price NUMBER NOT NULL,
    publish_date DATE NOT NULL,
    edition_number NUMBER NOT NULL,
    publisher_id NUMBER,
    CONSTRAINT PK_NEWSPAPER PRIMARY KEY (NEWSPAPER_ID),
    CONSTRAINT FK_NEWSPAPER_PUBLISHER FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS(PUBLISHER_ID) ON DELETE SET NULL 
)

CREATE TABLE NEWSPAPER_ITEMS (
    NEWSPAPER_ITEM_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NEWSPAPER_ID NUMBER NOT NULL,
    CONSTRAINT PK_NEWSPAPER_ITEM PRIMARY KEY (NEWSPAPER_ITEM_ID),
    CONSTRAINT FK_ITEM_NEWSPAPER FOREIGN KEY (NEWSPAPER_ID) REFERENCES NEWSPAPERS(NEWSPAPER_ID)
)

CREATE TABLE Penalties (
    penalty_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    CUSTOMER_ID NUMBER NOT NULL,
    BOOK_ITEM_ID NUMBER NOT NULL,
    PENALTY_FUNDS NUMBER NOT NULL,
    PENALTY_DUE_DATE DATE DEFAULT ADD_MONTHS(SYSDATE, 3) not null,
    CONSTRAINT PK_PENALTY PRIMARY KEY (PENALTY_ID),
    CONSTRAINT FK_PENALTY_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_PENALTY_BOOK_ITEM FOREIGN KEY (BOOK_ITEM_ID) REFERENCES BOOK_ITEMS(BOOK_ITEM_ID) ON DELETE CASCADE
)