insert into NEWSPAPER_ITEMS (NEWSPAPER_ID)
select 49 from dual union all
select 76 from dual union all
select 63 from dual union all
select 29 from dual union all
select 95 from dual union all
select 89 from dual union all
select 99 from dual union all
select 92 from dual union all
select 52 from dual union all
select 67 from dual union all
select 54 from dual union all
select 44 from dual union all
select 74 from dual union all
select 57 from dual union all
select 87 from dual union all
select 98 from dual union all
select 30 from dual union all
select 40 from dual union all
select 98 from dual union all
select 1 from dual union all
select 73 from dual union all
select 91 from dual union all
select 40 from dual union all
select 62 from dual union all
select 22 from dual union all
select 31 from dual union all
select 9 from dual union all
select 87 from dual union all
select 69 from dual union all
select 42 from dual union all
select 92 from dual union all
select 39 from dual union all
select 25 from dual union all
select 58 from dual union all
select 33 from dual union all
select 18 from dual union all
select 49 from dual union all
select 43 from dual union all
select 68 from dual union all
select 30 from dual union all
select 60 from dual union all
select 40 from dual union all
select 25 from dual union all
select 39 from dual union all
select 62 from dual union all
select 45 from dual union all
select 82 from dual union all
select 89 from dual union all
select 43 from dual union all
select 77 from dual union all
select 1 from dual union all
select 82 from dual union all
select 52 from dual union all
select 19 from dual union all
select 42 from dual union all
select 78 from dual union all
select 13 from dual union all
select 74 from dual union all
select 62 from dual union all
select 64 from dual union all
select 32 from dual union all
select 67 from dual union all
select 31 from dual union all
select 15 from dual union all
select 59 from dual union all
select 99 from dual union all
select 83 from dual union all
select 8 from dual union all
select 63 from dual union all
select 26 from dual union all
select 40 from dual union all
select 27 from dual union all
select 29 from dual union all
select 71 from dual union all
select 60 from dual union all
select 28 from dual union all
select 53 from dual union all
select 58 from dual union all
select 5 from dual union all
select 79 from dual union all
select 68 from dual union all
select 14 from dual union all
select 3 from dual union all
select 19 from dual union all
select 6 from dual union all
select 77 from dual union all
select 12 from dual union all
select 9 from dual union all
select 67 from dual union all
select 97 from dual union all
select 24 from dual union all
select 68 from dual union all
select 36 from dual union all
select 63 from dual union all
select 77 from dual union all
select 58 from dual union all
select 17 from dual union all
select 57 from dual union all
select 22 from dual union all
select 85 from dual;



--MAGAZINES 



insert into MAGAZINE_ITEMS (MAGAZINE_ID)
select 13 from dual union all
select 81 from dual union all
select 89 from dual union all
select 54 from dual union all
select 97 from dual union all
select 20 from dual union all
select 76 from dual union all
select 50 from dual union all
select 99 from dual union all
select 88 from dual union all
select 97 from dual union all
select 90 from dual union all
select 30 from dual union all
select 37 from dual union all
select 21 from dual union all
select 93 from dual union all
select 32 from dual union all
select 22 from dual union all
select 11 from dual union all
select 42 from dual union all
select 52 from dual union all
select 71 from dual union all
select 99 from dual union all
select 91 from dual union all
select 29 from dual union all
select 79 from dual union all
select 71 from dual union all
select 83 from dual union all
select 51 from dual union all
select 40 from dual union all
select 10 from dual union all
select 78 from dual union all
select 60 from dual union all
select 39 from dual union all
select 19 from dual union all
select 74 from dual union all
select 85 from dual union all
select 76 from dual union all
select 31 from dual union all
select 93 from dual union all
select 33 from dual union all
select 33 from dual union all
select 10 from dual union all
select 99 from dual union all
select 12 from dual union all
select 90 from dual union all
select 7 from dual union all
select 62 from dual union all
select 52 from dual union all
select 3 from dual union all
select 45 from dual union all
select 2 from dual union all
select 7 from dual union all
select 52 from dual union all
select 58 from dual union all
select 50 from dual union all
select 94 from dual union all
select 91 from dual union all
select 49 from dual union all
select 59 from dual union all
select 52 from dual union all
select 15 from dual union all
select 93 from dual union all
select 53 from dual union all
select 71 from dual union all
select 95 from dual union all
select 34 from dual union all
select 5 from dual union all
select 17 from dual union all
select 60 from dual union all
select 22 from dual union all
select 76 from dual union all
select 13 from dual union all
select 75 from dual union all
select 9 from dual union all
select 11 from dual union all
select 16 from dual union all
select 18 from dual union all
select 39 from dual union all
select 44 from dual union all
select 42 from dual union all
select 74 from dual union all
select 20 from dual union all
select 64 from dual union all
select 33 from dual union all
select 72 from dual union all
select 3 from dual union all
select 79 from dual union all
select 72 from dual union all
select 90 from dual union all
select 1 from dual union all
select 81 from dual union all
select 67 from dual union all
select 9 from dual union all
select 74 from dual union all
select 4 from dual union all
select 50 from dual union all
select 95 from dual union all
select 89 from dual union all
select 62 from dual;



-- BOOK ITEMS


insert into BOOK_ITEMS (BOOK_ID)
select 10 from dual union all
select 72 from dual union all
select 7 from dual union all
select 35 from dual union all
select 94 from dual union all
select 63 from dual union all
select 81 from dual union all
select 79 from dual union all
select 32 from dual union all
select 92 from dual union all
select 90 from dual union all
select 99 from dual union all
select 95 from dual union all
select 64 from dual union all
select 5 from dual union all
select 69 from dual union all
select 98 from dual union all
select 11 from dual union all
select 12 from dual union all
select 23 from dual union all
select 65 from dual union all
select 9 from dual union all
select 73 from dual union all
select 20 from dual union all
select 23 from dual union all
select 73 from dual union all
select 31 from dual union all
select 69 from dual union all
select 65 from dual union all
select 74 from dual union all
select 97 from dual union all
select 62 from dual union all
select 33 from dual union all
select 52 from dual union all
select 4 from dual union all
select 34 from dual union all
select 45 from dual union all
select 71 from dual union all
select 55 from dual union all
select 66 from dual union all
select 77 from dual union all
select 1 from dual union all
select 98 from dual union all
select 41 from dual union all
select 99 from dual union all
select 86 from dual union all
select 67 from dual union all
select 54 from dual union all
select 16 from dual union all
select 95 from dual union all
select 96 from dual union all
select 93 from dual union all
select 5 from dual union all
select 45 from dual union all
select 96 from dual union all
select 28 from dual union all
select 21 from dual union all
select 43 from dual union all
select 89 from dual union all
select 12 from dual union all
select 8 from dual union all
select 59 from dual union all
select 89 from dual union all
select 7 from dual union all
select 56 from dual union all
select 60 from dual union all
select 34 from dual union all
select 45 from dual union all
select 60 from dual union all
select 25 from dual union all
select 79 from dual union all
select 42 from dual union all
select 10 from dual union all
select 10 from dual union all
select 12 from dual union all
select 18 from dual union all
select 80 from dual union all
select 48 from dual union all
select 60 from dual union all
select 17 from dual union all
select 33 from dual union all
select 41 from dual union all
select 37 from dual union all
select 78 from dual union all
select 16 from dual union all
select 6 from dual union all
select 31 from dual union all
select 77 from dual union all
select 23 from dual union all
select 28 from dual union all
select 80 from dual union all
select 29 from dual union all
select 94 from dual union all
select 8 from dual union all
select 44 from dual union all
select 5 from dual union all
select 43 from dual union all
select 56 from dual union all
select 59 from dual union all
select 22 from dual;